name: rdkit_dev_template
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=h0ad9c76_8
  - c-compiler=1.11.0=h528c1b4_0
  - ca-certificates=2025.11.12=h4c7d964_0
  - cairo=1.18.4=h5782bbf_0
  - clang=19.1.7=default_hac490eb_5
  - clang-19=19.1.7=default_hac490eb_5
  - cmake=4.2.0=hdcbee5b_0
  - compiler-rt=19.1.7=h49e36cd_1
  - compiler-rt_win-64=19.1.7=h49e36cd_1
  - compilers=1.11.0=h57928b3_0
  - cxx-compiler=1.11.0=h1c1089f_0
  - eigen=3.4.0=h477610d_1
  - flang=19.1.7=hbeecb71_0
  - flang_impl_win-64=19.1.7=h719f0c7_0
  - flang_win-64=19.1.7=h719f0c7_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h765892d_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fortran-compiler=1.11.0=h95e3450_0
  - freetype=2.14.1=h57928b3_0
  - icu=75.1=he0c23c2_0
  - krb5=1.21.3=hdf4eb48_0
  - libboost=1.86.0=h9dfe17d_4
  - libboost-devel=1.86.0=h1c1089f_4
  - libboost-headers=1.86.0=h57928b3_4
  - libcurl=8.17.0=h43ecb02_0
  - libexpat=2.7.3=hac47afa_0
  - libffi=3.5.2=h52bdfb6_0
  - libflang=19.1.7=he0c23c2_0
  - libfreetype=2.14.1=h57928b3_0
  - libfreetype6=2.14.1=hdbac1cb_0
  - libglib=2.86.2=h0c9aed9_1
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libllvm19=19.1.7=h830ff33_2
  - liblzma=5.8.1=h2466b09_2
  - libpng=1.6.51=h7351971_0
  - librdkit=2025.09.3=h0cb3073_0
  - librdkit-dev=2025.09.3=h36c15f3_0
  - libssh2=1.11.1=h9aa295b_0
  - libuv=1.51.0=hfd05255_1
  - libxml2=2.15.1=ha29bfb0_0
  - libxml2-16=2.15.1=h06f855e_0
  - libzlib=1.3.1=h2466b09_2
  - lld=21.1.6=hc465015_0
  - llvm-tools=19.1.7=h752b59f_2
  - openssl=3.6.0=h725018a_0
  - pcre2=10.47=hd2b5f0e_0
  - pixman=0.46.4=h5112557_1
  - ucrt=10.0.26100.0=h57928b3_0
  - vc=14.3=h2b53caa_32
  - vc14_runtime=14.44.35208=h818238b_32
  - vcomp14=14.44.35208=h818238b_32
  - vs2022_win-64=19.44.35207=ha74f236_32
  - vswhere=3.1.7=h40126e0_1
  - zstd=1.5.7=h1b5488d_5
